version: 2.0
jobs:
  build:
    docker:
      - image: kpalcowski/ui-test
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          JAVA_OPTS: -Xmx3G
          SBT_OPTS: -Xms512M -Xmx3G -Xss1G -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=376M
          APP_HOST: https://app.imperative.com
          SLEEP_MILLIS: 86400000
          MAILER_FROM_NAME: Imperative Stress Tests
          MAILER_HOST: smtp.gmail.com
          MAILER_PORT: 587
          MAILER_START_TTLS: "true"
          GSERVICE_ACCOUNT_EMAIL: imperative@imperative-219010.iam.gserviceaccount.com
          GSERVICE_ACCOUNT_PKCS12_FILE_PATH: /opt/docker/key.p12
    steps:
      - run: /opt/docker/bin/ui-test
